### ISSUE TITLE
ナビゲーションのサブメニューのテキストが折り返されず文字が重なる

### ISSUE THREAD

**Issue by featherplain** [wct2018/wct2018#22]
@sinack 下記対応お願いします🙏

![image](https://user-images.githubusercontent.com/7019355/41810375-4364645a-7738-11e8-96e4-c722025e6f0a.png)

- サブメニューの Width を200 ~ 300px 程度にする
- テキストが長い場合は折り返されるようにする

**Comment by sinack** [comment]
@featherplain 
キャプチャで言うところの、Englishのサブメニューの表示位置で相談です！
今のサブメニューは`left:0`なので、
このままwidthを確保するとサブメニューが右側に突き抜けてしまいます。
かといってサブメニューを`right:0`すると左側にいるメニューがおかしいので、
やるなら右2つとかなのかなと思うんですが、
他にいいアイデアとかこうしたらいいのでは？っていうのがあればコメントほしいです。

**Comment by featherplain** [comment]
@sinack 
`li: last-child` の `.sub-menu` のみ `right: 0;` になるようにするのがいいかと思いました！

**Comment by sinack** [comment]
@featherplain 
わかりましたー！とりあえず今は右端突き抜けそうなサブメニューがEnglishだけなので、
`li:last-child`で対応しようと思います！

**Comment by featherplain** [comment]
#24 でマージしたのでクローズします🙆‍♀️
