### ISSUE TITLE
英語ページのフォントを英文フォント優先にする

### ISSUE THREAD

**Issue by naokomc** [wct2018/wct2018#33]
現在、[英語ページ](https://2018.tokyo.wordcamp.org/en/)でもフォント指定が以下のようになっているようです。

`font-family: "Hiragino Kaku Gothic ProN", "メイリオ", meiryo sans-serif;`

去年の[英語ページ](https://2017.tokyo.wordcamp.org/en/)では以下のとおりです。

`font-family: helvetica, arial, "Hiragino Kaku Gothic ProN", meiryo, "ms pgothic", sans-serif;`

フォントを変えると文字が小さくなる場合はこちらも参考にしてみてください（今年のデザインは全体的に大きめになっているので必要ないかも）。
https://github.com/wctokyo2017/wct2017/issues/26

**Comment by fumikito** [comment]
@naokomc  対応しました。
