### ISSUE TITLE
スピーカーページで、Gravatar がミステリーマンの場合非表示にする

### ISSUE THREAD

**Issue by featherplain** [wct2018/wct2018#49]

**Comment by fumikito** [comment]
主にスピーカーがGravatarを利用していない場合の対処だと思うのですが、

1. ミステリーマンの場合だけ非表示にし……
    1. 写真は表示しない
    2. 写真を手動で挿入する
1. 常にGravatarを非表示にし、すべて主導で挿入する（Gravatarショートコードを組み合わせる）

上記のパティーンがあると思うのですが、どれにしますか？　オススメは1の2です。
難点は、ショートコードでの自動挿入の場合、レイアウトが若干変わってしまう可能性があることです。

**Comment by naokomc** [comment]
テストしてる時に公開時に入ること気づかず、もう全部ショートコード OR 画像を入れてしまったので、2（常に非表示）でお願いできますか？
ありがとうございます 🙇

**Comment by featherplain** [comment]
@fumikito @naokomc 2 でいきましょう！

**Comment by fumikito** [comment]
なんかもう対応終わってましたね。

<img width="1440" alt="__wordcamp_tokyo_2018_ _challenge 2018 9 14 _15 2" src="https://user-images.githubusercontent.com/84587/44947465-5dd63d80-ae48-11e8-8bcf-2f170183cc80.png">

**Comment by featherplain** [comment]
@fumikito おお、なんと。。ありがとうございました🙇‍♀️

**Comment by naokomc** [comment]
すいません、タイムテーブル公開時に足しておいたのですがここに報告忘れていました。

@featherplain @fumikito 
ついでですいませんが、一応情報共有で、こちらも足しました（_s のデフォルト CSS からコピペ）
![image](https://user-images.githubusercontent.com/34067/45008850-d2270180-b03f-11e8-87de-5d379d38a95b.png)

（公開後更新されると、2つ日付が表示されるのを防ぐため）
