### ISSUE TITLE
セッション投稿タイプ上のスライドと動画のリンクをいい感じにする

### ISSUE THREAD

**Issue by naokomc** [wct2018/wct2018#52]
## セッション投稿タイプ

シェアボタンとの余白がないのが気になりますので、最低それだけ調整していただけると嬉しいです。もし余力あればもっと見つけやすく/かっこよくしていただいてもー。

表示例: [コスギさんのセッション](https://2018.tokyo.wordcamp.org/session/ef-5-2/)
![image](https://user-images.githubusercontent.com/34067/45658635-21cef800-bb2b-11e8-95e0-9ae43b3e182a.png)

多分バグの気がしますが、プレビューしただけではスライド・動画リンクが表示されません。まだ動画リンクがあるセッションはないので、ダミーリンクを入れて一時的にひっそり公開するか、インスペクターツールとかで表示確認してください 😓

**Comment by featherplain** [comment]
@naokomc 

<img src="https://user-images.githubusercontent.com/7019355/45764517-d7a25f80-bc6d-11e8-8327-c42efe7a9b5b.png" width="400px">


シェアボタンとの余白をつけ、リンクにボタンスタイルを適用しました！

![image](https://user-images.githubusercontent.com/7019355/45763501-8abd8980-bc6b-11e8-8777-5051719010be.png)

本当は各リンクにアイコンをつけるなどして差別化したかったのですが、マークアップが同じだったので見送りました😓( CSS 側で URL 判定すれば一応できるのですが。。 ) 登壇者名が元々あまり目立たないため、これを機にスタイル調整を色々と試みたのですが、なぜか CSS が効かず💧そのためこの状態で反映させてあります💦

**Comment by naokomc** [comment]
@featherplain ありがとうございましたー！
見やすくて、良いと思います！
マウスオーバーした時に下に細い青い線が出るのは意図した挙動でしょうか？

![screencast-2018 tokyo wordcamp org-2018 09 21-11-51-21](https://user-images.githubusercontent.com/34067/45857704-08c97f80-bd95-11e8-8540-cb61d5508688.gif)

**Comment by featherplain** [comment]
@naokomc 

<img src="https://user-images.githubusercontent.com/7019355/45857982-3c58d980-bd96-11e8-9734-1da8a4ef3048.gif" width="400px">


おおー！>< それは意図しない挙動でした、今直して反映させました💦
hover 時に `border-bottom` が適用されていたようです😓

**Comment by naokomc** [comment]
早速の対応ありがとうございました！
バッチリです 💯
